const VODefinitions = {
    Money: [
        {
            className: "Double",
            isKey: false,
            label: "- amount: Double",
            name: "amount",
            nameCamelCase: "amount",
            namePascalCase: "Amount",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- currency: String",
            name: "currency",
            nameCamelCase: "currency",
            namePascalCase: "Currency",
            _type: "org.uengine.model.FieldDescriptor",
        },
    ],
    Email: [
        {
            className: "String",
            isKey: false,
            label: "- email: String",
            name: "email",
            nameCamelCase: "email",
            namePascalCase: "Email",
            _type: "org.uengine.model.FieldDescriptor",
        },
        // {
        //     className: "String",
        //     isKey: false,
        //     label: "- subject: String",
        //     name: "subject",
        //     nameCamelCase: "subject",
        //     namePascalCase: "Subject",
        //     _type: "org.uengine.model.FieldDescriptor",
        // },
        // {
        //     className: "String",
        //     isKey: false,
        //     label: "- content: String",
        //     name: "content",
        //     nameCamelCase: "content",
        //     namePascalCase: "Content",
        //     _type: "org.uengine.model.FieldDescriptor",
        // },
    ],
    Likes: [
        {
            className: "Boolean",
            isKey: false,
            label: "- isLiked: Boolean",
            name: "isLiked",
            nameCamelCase: "isLiked",
            namePascalCase: "IsLiked",
            _type: "org.uengine.model.FieldDescriptor",
        },
    ],
    File: [
        {
            className: "String",
            isKey: false,
            label: "- fileName: String",
            name: "fileName",
            nameCamelCase: "fileName",
            namePascalCase: "FileName",
            _type: "org.uengine.model.FieldDescriptor",
            isLob: true,
            isVO: false,
            isList: false,
            isName: false,
        },
        {
            className: "String",
            isKey: false,
            label: "- file: String",
            name: "file",
            nameCamelCase: "file",
            namePascalCase: "File",
            _type: "org.uengine.model.FieldDescriptor",
            isLob: true,
            isVO: false,
            isList: false,
            isName: false,
        },
    ],
    Payment: [
        {
            className: "String",
            isKey: false,
            label: "- paymentType: String",
            name: "paymentType",
            nameCamelCase: "paymentType",
            namePascalCase: "PaymentType",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "Double",
            isKey: false,
            label: "- amount: Double",
            name: "amount",
            nameCamelCase: "amount",
            namePascalCase: "Amount",
            _type: "org.uengine.model.FieldDescriptor",
        },
    ],
    Photo: [
        {
            className: "String",
            isKey: false,
            label: "- imgName: String",
            name: "imgName",
            nameCamelCase: "imgName",
            namePascalCase: "ImgName",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- imgFile: String",
            name: "imgFile",
            nameCamelCase: "imgFile",
            namePascalCase: "ImgFile",
            _type: "org.uengine.model.FieldDescriptor",
            isLob: true,
        },
    ],
    Tags: [
        {
            className: "List<String>",
            isKey: false,
            label: "- tag: List<String>",
            name: "tag",
            nameCamelCase: "tag",
            namePascalCase: "Tag",
            _type: "org.uengine.model.FieldDescriptor",
        },
    ],
    User: [
        {
            className: "String",
            isKey: false,
            label: "- userId: String",
            name: "userId",
            nameCamelCase: "userId",
            namePascalCase: "UserId",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- password: String",
            name: "password",
            nameCamelCase: "password",
            namePascalCase: "Password",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- name: String",
            name: "name",
            nameCamelCase: "name",
            namePascalCase: "Name",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- email: String",
            name: "email",
            nameCamelCase: "email",
            namePascalCase: "Email",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- address: String",
            name: "address",
            nameCamelCase: "address",
            namePascalCase: "Address",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- phone: String",
            name: "phone",
            nameCamelCase: "phone",
            namePascalCase: "Phone",
            _type: "org.uengine.model.FieldDescriptor",
        },
    ],
    Weather: [
        {
            className: "Double",
            isKey: false,
            label: "- degree: Double",
            name: "degree",
            nameCamelCase: "degree",
            namePascalCase: "Degree",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "Double",
            isKey: false,
            label: "- precipitation: Double",
            name: "precipitation",
            nameCamelCase: "precipitation",
            namePascalCase: "Precipitation",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "Double",
            isKey: false,
            label: "- humidity: Double",
            name: "humidity",
            nameCamelCase: "humidity",
            namePascalCase: "Humidity",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "Double",
            isKey: false,
            label: "- wind: Double",
            name: "wind",
            nameCamelCase: "wind",
            namePascalCase: "Wind",
            _type: "org.uengine.model.FieldDescriptor",
        },
    ],
    Address: [
        {
            className: "String",
            isKey: false,
            label: "- street: String",
            name: "street",
            nameCamelCase: "street",
            namePascalCase: "Street",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- city: String",
            name: "city",
            nameCamelCase: "city",
            namePascalCase: "City",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- state: String",
            name: "state",
            nameCamelCase: "state",
            namePascalCase: "State",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- country: String",
            name: "country",
            nameCamelCase: "country",
            namePascalCase: "Country",
            _type: "org.uengine.model.FieldDescriptor",
        },
        {
            className: "String",
            isKey: false,
            label: "- zipcode: String",
            name: "zipcode",
            nameCamelCase: "zipcode",
            namePascalCase: "ZipCode",
            _type: "org.uengine.model.FieldDescriptor",
        },
    ],
    Comment: [
        {
            className: "List<String>",
            isKey: false,
            label: "- content: List<String>",
            name: "content",
            nameCamelCase: "content",
            namePascalCase: "Content",
            _type: "org.uengine.model.FieldDescriptor",
        },
    ],
    Rating: [
        {
            className: "List<String>",
            isKey: false,
            label: "- content: List<String>",
            name: "content",
            nameCamelCase: "content",
            namePascalCase: "Content",
            _type: "org.uengine.model.FieldDescriptor",
        },
    ],
}

module.exports = VODefinitions;